export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const ADD_USERINFO = 'ADD_USERINFO';
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';
export const GET_DATA = 'GET_DATA';
